package agendaestudiantil;

import java.awt.Window;
import java.awt.event.WindowAdapter;
import java.util.InputMismatchException;
import java.util.List;
import javax.mail.MessagingException;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;

public class Interfaz extends javax.swing.JFrame {

    /**
     * Creates new form Interfaz
     */
    public Interfaz() {
        initComponents();
        loadTableData(HorarioTable, "horario");
        loadTableData(EvaluacionesTable, "evaluacion");
        loadTableData(TareasTable, "tareas");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        TabbedPaneInterfaz = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        comboBoxSemestre = new javax.swing.JComboBox<>();
        comboBoxDia = new javax.swing.JComboBox<>();
        btnAgregarMateria = new javax.swing.JButton();
        btnEliminarMateria = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        HorarioTable = new javax.swing.JTable();
        btnActualizar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        comboBoxSemestreEvaluacion = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        EvaluacionesTable = new javax.swing.JTable();
        btnEvaluacion = new javax.swing.JButton();
        btnActualizarEvaluaciones = new javax.swing.JButton();
        btnImprimir = new javax.swing.JToggleButton();
        jPanel3 = new javax.swing.JPanel();
        comboBoxTareas = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        TareasTable = new javax.swing.JTable();
        btnAgregarTarea = new javax.swing.JButton();
        btnEliminarTarea = new javax.swing.JButton();
        btnActualizarTareas = new javax.swing.JButton();
        btnEnviar = new javax.swing.JButton();
        btnAjustesCorreo = new javax.swing.JButton();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TabbedPaneInterfaz.setName("Agenda Estudiantil"); // NOI18N
        TabbedPaneInterfaz.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                TabbedPaneInterfazFocusGained(evt);
            }
        });

        comboBoxSemestre.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Semestre 1", "Semestre 2", "Semestre 3", "Semestre 4", "Semestre 5", "Semestre 7", "Semestre 8", "Semestre 9" }));
        comboBoxSemestre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxSemestreActionPerformed(evt);
            }
        });

        comboBoxDia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Lunes", "Martes", "Miercoles", "Jueves", "Viernes", "Sabados", "Domingo" }));
        comboBoxDia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxDiaActionPerformed(evt);
            }
        });

        btnAgregarMateria.setText("+");
        btnAgregarMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarMateriaActionPerformed(evt);
            }
        });

        btnEliminarMateria.setText("-");
        btnEliminarMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarMateriaActionPerformed(evt);
            }
        });

        jScrollPane3.setViewportView(HorarioTable);

        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(comboBoxDia, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(97, 97, 97)
                        .addComponent(comboBoxSemestre, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                        .addComponent(btnActualizar))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 499, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnAgregarMateria, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE)
                            .addComponent(btnEliminarMateria, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboBoxSemestre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboBoxDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnActualizar))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnAgregarMateria)
                        .addGap(18, 18, 18)
                        .addComponent(btnEliminarMateria)))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        TabbedPaneInterfaz.addTab("Materias", jPanel1);

        jPanel2.setName(""); // NOI18N

        comboBoxSemestreEvaluacion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Semestre 1", "Semestre 2", "Semestre 3", "Semestre 4", "Semestre 5", "Semestre 6", "Semestre 7", "Semestre 8", "Semestre 9", " " }));
        comboBoxSemestreEvaluacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxSemestreEvaluacionActionPerformed(evt);
            }
        });

        EvaluacionesTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        EvaluacionesTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(EvaluacionesTable);
        EvaluacionesTable.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);

        btnEvaluacion.setText("Evaluación");
        btnEvaluacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEvaluacionMouseClicked(evt);
            }
        });
        btnEvaluacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEvaluacionActionPerformed(evt);
            }
        });

        btnActualizarEvaluaciones.setText("Actualizar");
        btnActualizarEvaluaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarEvaluacionesActionPerformed(evt);
            }
        });

        btnImprimir.setText("Imprimir");
        btnImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImprimirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(comboBoxSemestreEvaluacion, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 321, Short.MAX_VALUE))
                    .addComponent(jScrollPane1))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnEvaluacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnActualizarEvaluaciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnImprimir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboBoxSemestreEvaluacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnActualizarEvaluaciones))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnEvaluacion, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnImprimir)))
                .addGap(36, 36, 36))
        );

        TabbedPaneInterfaz.addTab("Evaluaciones", jPanel2);

        comboBoxTareas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hoy", "Mañana", "Esta semana", "Próxima semana", "Este mes", "Este año", "Todas" }));
        comboBoxTareas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxTareasActionPerformed(evt);
            }
        });

        jScrollPane2.setViewportView(TareasTable);

        btnAgregarTarea.setText("+");
        btnAgregarTarea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarTareaActionPerformed(evt);
            }
        });

        btnEliminarTarea.setText("-");
        btnEliminarTarea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarTareaActionPerformed(evt);
            }
        });

        btnActualizarTareas.setText("Actualizar");
        btnActualizarTareas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarTareasActionPerformed(evt);
            }
        });

        btnEnviar.setText("Enviar");
        btnEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviarActionPerformed(evt);
            }
        });

        btnAjustesCorreo.setText("Ajustes");
        btnAjustesCorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAjustesCorreoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 499, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboBoxTareas, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnActualizarTareas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAgregarTarea, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEliminarTarea, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEnviar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAjustesCorreo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboBoxTareas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnActualizarTareas))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btnAgregarTarea)
                        .addGap(18, 18, 18)
                        .addComponent(btnEliminarTarea)
                        .addGap(18, 18, 18)
                        .addComponent(btnEnviar)
                        .addGap(18, 18, 18)
                        .addComponent(btnAjustesCorreo))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        TabbedPaneInterfaz.addTab("Tareas", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TabbedPaneInterfaz)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TabbedPaneInterfaz)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comboBoxSemestreEvaluacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxSemestreEvaluacionActionPerformed
        loadTableData(EvaluacionesTable, "evaluacion");
    }//GEN-LAST:event_comboBoxSemestreEvaluacionActionPerformed

    private void btnAgregarMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarMateriaActionPerformed
        AgregarMateriaDialog agregarDialog = new AgregarMateriaDialog(this, true);
        
        agregarDialog.addWindowListener(new WindowAdapter() {
            public void windowClosed(Window e) {
                loadTableData(HorarioTable, "horario");
                System.out.println("Se cerró el dialog");
            }
        });
        agregarDialog.setVisible(true);
    }//GEN-LAST:event_btnAgregarMateriaActionPerformed

    private void comboBoxDiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxDiaActionPerformed
        loadTableData(HorarioTable, "horario");
    }//GEN-LAST:event_comboBoxDiaActionPerformed

    private void comboBoxSemestreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxSemestreActionPerformed
        loadTableData(HorarioTable, "horario");
    }//GEN-LAST:event_comboBoxSemestreActionPerformed

    private void btnEvaluacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEvaluacionActionPerformed
        String codigo = (String) EvaluacionesTable.getValueAt(EvaluacionesTable.getSelectedRow(), 0);
        EvaluacionesDialog dialog = new EvaluacionesDialog(this, true);
        dialog.setTitle(codigo);
        dialog.setMateria(codigo);
        dialog.setVisible(true);
    }//GEN-LAST:event_btnEvaluacionActionPerformed

    private void btnEvaluacionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEvaluacionMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEvaluacionMouseClicked

    private void btnAgregarTareaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarTareaActionPerformed
        AgregarTarea agregarTareasDialog = new AgregarTarea(this, true);
        agregarTareasDialog.setVisible(true);
    }//GEN-LAST:event_btnAgregarTareaActionPerformed

    private void btnEliminarMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarMateriaActionPerformed
        String codigo = (String) HorarioTable.getValueAt(HorarioTable.getSelectedRow(), 2);
        DB.delete(codigo);
        loadTableData(HorarioTable, "horario");
    }//GEN-LAST:event_btnEliminarMateriaActionPerformed

    private void TabbedPaneInterfazFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TabbedPaneInterfazFocusGained
        loadTableData(HorarioTable, "horario");
    }//GEN-LAST:event_TabbedPaneInterfazFocusGained

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        loadTableData(HorarioTable, "horario");
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnActualizarEvaluacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarEvaluacionesActionPerformed
        loadTableData(EvaluacionesTable, "evaluacion");
    }//GEN-LAST:event_btnActualizarEvaluacionesActionPerformed

    private void btnActualizarTareasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarTareasActionPerformed
        List<Tarea> tareasPorRecordar = DB.getTodayTareas();
        for (Tarea t : tareasPorRecordar) {
            try {
                Mail.sendMail(t);
            } catch(MessagingException e) {
                JOptionPane.showMessageDialog(null, "Error al enviar recordatorio");
            } catch (InputMismatchException i) {
                JOptionPane.showMessageDialog(null, "Configure su correo para recibir los recordatorios");
            }
        }
        loadTableData(TareasTable, "tareas");
    }//GEN-LAST:event_btnActualizarTareasActionPerformed

    private void comboBoxTareasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxTareasActionPerformed
        loadTableData(TareasTable, "tareas");
    }//GEN-LAST:event_comboBoxTareasActionPerformed

    private void btnEliminarTareaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarTareaActionPerformed
       String tarea = (String) TareasTable.getValueAt(TareasTable.getSelectedRow(), 1);
       DB.deleteTarea(tarea);
       loadTableData(TareasTable, "tareas");
    }//GEN-LAST:event_btnEliminarTareaActionPerformed

    private void btnImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImprimirActionPerformed
        try {
            DB.conectar();
            String dir = "../../../reporteKardex.jrxml";
            JasperReport reporteJasper = JasperCompileManager.compileReport(dir);
            JasperPrint mostrarReporte = JasperFillManager.fillReport(reporteJasper, null, DB.getConnection());
            JasperViewer.viewReport(mostrarReporte);
        } catch (JRException ex) {
            JOptionPane.showMessageDialog(null, "Error al imprimir archivo");
            ex.printStackTrace();
        } finally {
            DB.desconectar();
        }
    }//GEN-LAST:event_btnImprimirActionPerformed

    private void btnEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarActionPerformed
        /*try {
            sendMail();
        } catch (MessagingException e) {
            JOptionPane.showMessageDialog(null, "Error al enviar correo");
        }*/
    }//GEN-LAST:event_btnEnviarActionPerformed

    private void btnAjustesCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAjustesCorreoActionPerformed
        AjustesCorreoDialog ajustesDialog = new AjustesCorreoDialog(this, true);
        ajustesDialog.setVisible(true);
    }//GEN-LAST:event_btnAjustesCorreoActionPerformed
    
    private void loadTableData(JTable table, String mode) {
        switch (mode) {
            case "horario":
                table.setModel(DB.buildTableModel("SELECT hora_inicio, hora_fin, codigo, nombre, aula FROM agenda.materias WHERE FIND_IN_SET('"
                + comboBoxDia.getSelectedItem().toString() + "', dias)>0 AND semestre="
                + (comboBoxSemestre.getSelectedIndex() + 1) + " ORDER BY hora_inicio"));
                break;
            
            case "evaluacion":
                table.setModel(DB.buildTableModel("SELECT codigo, maestro, promedio FROM agenda.materias"
                + " WHERE semestre=" + (comboBoxSemestreEvaluacion.getSelectedIndex() + 1)));
                break;
                
            case "tareas":
                switch(comboBoxTareas.getSelectedIndex()) {
                    case 0: // Hoy
                        table.setModel(DB.buildTableModel("SELECT materia, tarea, fecha_entrega, fecha_recordatorio, recordatorio_enviado" 
                        + " FROM agenda.tareas WHERE day(fecha_entrega) = day(curdate()) ORDER BY fecha_entrega"));
                        break;
                        
                    case 1: // Mañana
                        table.setModel(DB.buildTableModel("SELECT materia, tarea, fecha_entrega, fecha_recordatorio, recordatorio_enviado" 
                        + " FROM agenda.tareas WHERE day(fecha_entrega) = day(curdate() + interval 1 day) ORDER BY fecha_entrega"));
                        break;
                        
                    case 2: // Esta semana
                        table.setModel(DB.buildTableModel("SELECT materia, tarea, fecha_entrega, fecha_recordatorio, recordatorio_enviado" 
                        + " FROM agenda.tareas WHERE yearweek(fecha_entrega) = yearweek(now()) ORDER BY fecha_entrega"));
                        break;
                        
                    case 3: // Próxima semana
                        table.setModel(DB.buildTableModel("SELECT materia, tarea, fecha_entrega, fecha_recordatorio, recordatorio_enviado" 
                        + " FROM agenda.tareas WHERE yearweek(fecha_entrega) = yearweek(now() + interval 1 week) ORDER BY fecha_entrega"));
                        break;
                        
                    case 4: // Este mes
                        table.setModel(DB.buildTableModel("SELECT materia, tarea, fecha_entrega, fecha_recordatorio, recordatorio_enviado" 
                        + " FROM agenda.tareas WHERE month(fecha_entrega) = month(curdate()) ORDER BY fecha_entrega"));
                        break;
                        
                    case 5: // Este año
                        table.setModel(DB.buildTableModel("SELECT materia, tarea, fecha_entrega, fecha_recordatorio, recordatorio_enviado" 
                        + " FROM agenda.tareas WHERE year(fecha_entrega) = year(curdate()) ORDER BY fecha_entrega"));
                        break;
                        
                    default:
                        table.setModel(DB.buildTableModel("SELECT materia, tarea, fecha_entrega, fecha_recordatorio, recordatorio_enviado" 
                        + " FROM agenda.tareas ORDER BY fecha_entrega"));
                        break;
                }                
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable EvaluacionesTable;
    private javax.swing.JTable HorarioTable;
    private javax.swing.JTabbedPane TabbedPaneInterfaz;
    private javax.swing.JTable TareasTable;
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnActualizarEvaluaciones;
    private javax.swing.JButton btnActualizarTareas;
    private javax.swing.JButton btnAgregarMateria;
    private javax.swing.JButton btnAgregarTarea;
    private javax.swing.JButton btnAjustesCorreo;
    private javax.swing.JButton btnEliminarMateria;
    private javax.swing.JButton btnEliminarTarea;
    private javax.swing.JButton btnEnviar;
    private javax.swing.JButton btnEvaluacion;
    private javax.swing.JToggleButton btnImprimir;
    private javax.swing.JComboBox<String> comboBoxDia;
    private javax.swing.JComboBox<String> comboBoxSemestre;
    private javax.swing.JComboBox<String> comboBoxSemestreEvaluacion;
    private javax.swing.JComboBox<String> comboBoxTareas;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    // End of variables declaration//GEN-END:variables
}
